web-app/django_project/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from users import views as user_views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', user_views.register, name='register'),
    path('profile/', user_views.profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('', include('ride.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web-app/ride/urls.py
from django.urls import path
from .views import (
            RideListView,
            RideDetailView,
            RideCreateView,
            RideUpdateView,
            RideDeleteView,
            OwnerRideListView,
            ShareCreateView,
            SharePickRideListView,
            ShareRideListView,
            DriverListView,
            ShareUpdateView
            )
from . import views
from .models import Ride, Share
from django.contrib.auth import views as auth_views

app_name = 'ride'
urlpatterns = [
    path('', auth_views.LoginView.as_view(template_name='users/login.html')),
    path('home/', views.home, name='ride-home'),
    # path('about/', views.about, name='ride-about'),
    path('owner/', views.owner, name='owner-home'),
    path('sharer/', views.sharer, name='sharer-home'),
    path('driver/', views.driver, name='driver-home'),
    path('owner/request/', RideCreateView.as_view(), name='owner-request'),
    path('driver/request/', DriverListView.as_view(), name='driver-request'),
    path('owner/view/', OwnerRideListView.as_view(), name='owner-view'),
    path('ride/<int:pk>/', RideDetailView.as_view(), name='ride-detail'),
    path('owner/view/<int:pk>/update/', RideUpdateView.as_view(), name='owner-update'),
    path('owner/view/<int:pk>/delete/', RideDeleteView.as_view(), name='owner-delete'),
    path('driver/<int:ride_id>/confirm/', views.driver_confirm, name='driver-confirm'),
    path('driver/<int:ride_id>/complete/', views.driver_complete, name='driver-complete'),
    path('sharer/request/', ShareCreateView.as_view(), name='share-request'),
    path('sharer/list/', SharePickRideListView.as_view(), name='share-list'),
    path('sharer/<int:ride_id>/join/', views.share_join, name='share-join'),
    path('sharer/<int:ride_id>/cancel/', views.share_cancel, name='share-cancel'),
    # path('sharer/view/', ShareRideListView.as_view(), name='share-view'),
    path('sharer/view/', views.share_view, name='share-view'),
    path('sharer/<int:pk>/update/', ShareUpdateView.as_view(), name='share-update'),
    path('driver/view/', views.driver_view, name='driver-view'),
]

web-app/ride/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.

class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    date_posted = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

class Ride(models.Model):

    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    des = models.CharField(max_length=200, verbose_name='Destination')
    start_date = models.DateTimeField(verbose_name='Start Date', help_text='Format: 2019-01-01 12:00')
    arrive_date = models.DateTimeField(verbose_name='Arrive Date', help_text='Format: 2019-01-01 12:00')
    pas_num = models.IntegerField(verbose_name='Passenger Number')
    share_valid = models.BooleanField(default=False, verbose_name='Do you want to share the ride with others?')
    share_max_num = models.IntegerField(verbose_name='The maximum sharers you can accept')
    share_name = models.CharField(max_length=200)
    share_number = models.IntegerField(default=0, verbose_name='Sharer Number')
    driver_name = models.CharField(max_length=200)
    status = models.IntegerField(default=0, verbose_name='Ride Status (open, confirmed, complete)')
    vehicle_type = models.CharField(max_length=200, verbose_name='Vehicle Type', blank=True)
    license_plate_number = models.CharField(max_length=20, verbose_name="License Plate Number", blank=True)
    max_pas_num = models.IntegerField(verbose_name="Maxmium Number of Passengers", default=0)
    # status: 0(open), 1(confirmed), 2(complete)

    def get_absolute_url(self):
        return reverse('ride:owner-view')

class Share(models.Model):

    sharer = models.ForeignKey(User, on_delete=models.CASCADE, default='')
    des = models.CharField(max_length=200, verbose_name='Destination')
    start_date_0 = models.DateTimeField(verbose_name='Earliest acceptable start date', help_text='Format: 2019-01-01 12:00')
    start_date_1 = models.DateTimeField(verbose_name='Latest acceptable start date', help_text='Format: 2019-01-01 12:00')
    arrive_date_0 = models.DateTimeField(verbose_name='Earliest acceptable arrive date', help_text='Format: 2019-01-01 12:00')
    arrive_date_1 = models.DateTimeField(verbose_name='Latest acceptable arrive date', help_text='Format: 2019-01-01 12:00')
    pas_num = models.IntegerField(default=1)

    def get_absolute_url(self):
        #return reverse('ride:ride-detail', kwargs={'pk': self.pk})
        return reverse('ride:share-list')

web-app/ride/forms.py
from django import forms
from .models import Ride
from .models import Share

class RideCreationForm(forms.ModelForm):
    class Meta:
        model = Ride
        fields = ['des', 'start_date', 'arrive_date', 'pas_num', 'share_valid', 'share_max_num']

        start_date = forms.DateField(
            widget = forms.DateInput(
                attrs= {
                        'type':'date',
                        }
            )
        )

class SharePickForm(forms.ModelForm):
    class Meta:
        model = Share
        fields = ['des', 'start_date_0', 'start_date_1', 'arrive_date_0', 'arrive_date_1', 'pas_num']

class ShareUpdateForm(forms.ModelForm):
    class Meta:
        model = Ride
        fields = ['share_number']

web-app/ride/views.py
from django.contrib import messages
from .models import Post
from django.shortcuts import redirect, render
from .forms import RideCreationForm, ShareUpdateForm
from .models import Ride, Share
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.core.mail import send_mail
from django.contrib.auth.models import User

# Create your views here.
def home(request):
    context = {
        'posts': Post.objects.all()
    }
    return render(request, 'ride/home.html', context)

def about(request):
    return render(request, 'ride/about.html', {'title': 'About'})

def owner(request):
    return render(request, 'ride/owner.html')

def sharer(request):
    return render(request, 'ride/sharer.html')

def driver(request):
    return render(request, 'ride/driver.html')

class RideListView(ListView):
    model = Ride

class OwnerRideListView(ListView):
    template_name = 'ride/ride_list.html'
    def get_queryset(self):
        return Ride.objects.filter(owner=self.request.user).exclude(status=2).order_by('-start_date')

class ShareRideListView(ListView):
    def get_queryset(self):
        return Ride.objects.filter(share_name=self.request.user.username).exclude(status=2).order_by('-start_date')

class DriverListView(ListView):
    template_name = 'ride/driver_list.html'
    def get_queryset(self):
        return Ride.objects.filter(status=0, pas_num__lte=self.request.user.profile.max_pas_num).order_by('-start_date')

def share_view(request):
    context = {
        'object_list': Ride.objects.filter(share_name=request.user.username).exclude(status=2).order_by('-start_date')
    }
    return render(request, 'ride/share_view.html', context)

def driver_view(request):
    context = {
        'object_list': Ride.objects.filter(driver_name=request.user.username).exclude(status=2).order_by('-start_date')
    }
    return render(request, 'ride/driver_view.html', context)

class SharePickRideListView(ListView):
    template_name = 'ride/share_list.html' # <app>/<model>_<viewtype>.html
    def get_queryset(self):
        share = self.request.user.share_set.last()
        return Ride.objects.filter(share_valid=True,
                                   des=share.des,
                                   start_date__gte=share.start_date_0,
                                   start_date__lte=share.start_date_1,
                                   arrive_date__gte=share.arrive_date_0,
                                   arrive_date__lte=share.arrive_date_1,
                                   pas_num__gte=share.pas_num,
                                   status=0
                                   ).exclude(owner=self.request.user).order_by('-start_date')

class ShareCreateView(LoginRequiredMixin, CreateView):
    model = Share
    fields = ['des', 'start_date_0', 'start_date_1', 'arrive_date_0', 'arrive_date_1', 'pas_num']
    #success_url = "{% url 'ride:share-list' %}"

    def form_valid(self, form):
        form.instance.sharer = self.request.user
        return super().form_valid(form)

class ShareRideListView(ListView):
    def get_queryset(self):
        return Ride.objects.filter(owner=self.request.user).exclude(status=2).order_by('-start_date')

class RideDetailView(DetailView):
    model = Ride

class RideCreateView(LoginRequiredMixin, CreateView):
    model = Ride
    fields = ['des', 'start_date', 'arrive_date', 'pas_num', 'share_valid', 'share_max_num']

    # def get_form(self):
    #     form = super(RideCreateView, self).get_form()
    #     form.fields['start_date'].widget.attrs.update({'class': 'datepicker'})
    #     return form

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)

class RideUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Ride
    fields = ['des', 'start_date', 'arrive_date', 'pas_num', 'share_valid', 'share_max_num']

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)

    def test_func(self):
        ride = self.get_object()
        if self.request.user == ride.owner:
            return True
        return False

class ShareUpdateView(LoginRequiredMixin, UpdateView):
    model = Ride
    fields = ['share_number']

class RideDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Ride
    success_url = '/owner/view/'

    def test_func(self):
        ride = self.get_object()
        if self.request.user == ride.owner:
            return True
        return False

def owner_request(request):
    if request.method == 'POST':
        form = RideCreationForm(request.POST)
        if form.is_valid():
            #form.owner_name = request.user.username
            form.save()
            #record = RequestRide.objects.last()
            #record.owner_name = request.user.username
            #form.save()
            messages.success(request, f'Your request has been created!')
            return redirect('ride:owner-home')
    else:
        form = RideCreationForm(request.POST)
    context = {
        'form': form,
    }
    return render(request, 'ride/owner_request.html', context)


def share_update(request, ride_id):
    if request.method == 'POST':
        form = ShareUpdateForm(request.POST)
        if form.is_valid():
            #form.owner_name = request.user.username
            form.save()
            #record = RequestRide.objects.last()
            #record.owner_name = request.user.username
            #form.save()
            messages.success(request, f'Your ride has been updated!')
            return redirect('ride:share-view')
    else:
        form = ShareUpdateForm(request.POST)
    context = {
        'form': form,
    }
    return render(request, 'ride/share_update.html', context)

def owner_view(request):
    Records = RequestRide.objects.filter(owner_name=request.user.username).exclude(status = 2)
    #Records = RequestRide.objects.exclude(status = 2)
    return render(request, 'ride/owner_view.html', {'Records': Records})

def owner_edit(request, request_id):
    record = RequestRide.objects.filter(pk = request_id).first()
    if request.method == 'POST':
        form = RideCreationForm(request.POST, instance=record)
        if form.is_valid():
            form.save()
            messages.success(request, f'Your request has been updated!')
            return redirect('ride:owner_view')
    else:
        form = RideCreationForm(instance=record)
    context = {
        'form': form,
    }
    return render(request, 'ride/owner_edit.html', context)

def share_join(request, ride_id):
    ride = Ride.objects.filter(pk=ride_id).first()
    share = Share.objects.all().last()
    ride.share_number = share.pas_num
    ride.share_name = request.user.username
    ride.save()
    return redirect('ride:share-list')

def share_cancel(request, ride_id):
    ride = Ride.objects.filter(pk=ride_id).first()
    share = Share.objects.all().last()
    ride.share_number = 0
    ride.share_name = 0
    ride.save()
    return redirect('ride:share-view')

def driver_confirm(request, ride_id):
    ride = Ride.objects.filter(pk=ride_id).first()
    sharer = User.objects.filter(username=ride.share_name).first()
    ride.driver_name = request.user.username
    ride.status = 1  # 1: confirmed
    ride.vehicle_type = request.user.profile.vehicle_type
    ride.license_plate_number = request.user.profile.license_plate_number
    ride.max_pas_num = request.user.profile.max_pas_num
    ride.save()
    send_mail(
        'Ride Confirmation Reminder',
        'Hi. You picked the ride successfully. Have a good trip!',
        'Duke myuber team',
        [request.user.email],
        fail_silently=False,
    )
    send_mail(
        'Ride Confirmation Reminder',
        'Hi. The ride that you requested has been confirmed by a driver successfully. Have a good trip!',
        'Duke myuber team',
        [ride.owner.email],
        fail_silently=False,
    )
    if sharer:
        send_mail(
            'Ride Confirmation Reminder',
            'Hi. The ride that you want to share has been confirmed by a driver successfully. Have a good trip!',
            'Duke myuber team',
            [sharer.email],
            fail_silently=False,
        )
    return redirect('ride:driver-request')

def driver_complete(request, ride_id):
    ride = Ride.objects.filter(pk=ride_id).first()
    ride.driver_name = request.user.username
    ride.status = 2  # 2: complete
    ride.save()
    return redirect('ride:driver-view')

web-app/ride/templates/ride/about.html
{% extends 'ride/base.html' %}

{% block content %}
    <h1>About page</h1>
{% endblock content %}

web-app/ride/templates/ride/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{% static 'ride/main.css' %}">

    {% if title %}
        <title>Myuber - {{ title }}</title>
    {% else %}
        <title>Myuber</title>
    {% endif %}
</head>
<body>
    <!-- Navigation Bar -->
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="{% url 'ride:ride-home' %}">Myuber</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{% url 'ride:ride-home' %}">Home</a>
              
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
                {% if user.is_authenticated %}
                  <a class="nav-item nav-link" href="{% url 'profile' %}">Profile</a>
                  <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>
                {% else %}
                  <a class="nav-item nav-link" href="{% url 'login' %}">Login</a>
                  <a class="nav-item nav-link" href="{% url 'register' %}">Register</a>
                {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>

    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
          {% if messages %}
              {% for message in messages %}
                  <dir class="alert-{{ message.tags }}">
                      {{ message }}
                  </dir>
              {% endfor %}
          {% endif %}
          {% block content %}{% endblock %}
        </div>
      </div>
    </main>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

web-app/ride/templates/ride/driver.html
{% extends 'ride/base.html' %}

{% block content %}
<h1>Which Action Do You Want?</h1>
<div>
    <button onclick="window.location.href='{% url 'ride:driver-request' %}'">Pick a ride request</button> <br><br>
    <button onclick="window.location.href='{% url 'ride:driver-view' %}'">View ride history</button> <br><br>
</div>
{% endblock content %}

web-app/ride/templates/ride/driver_view.html
{% extends 'ride/base.html' %}
{% block content %}
<table class="table table-striped table-bordered">
  <tr>
    <th>Status</th>
    <th>Complete</th>
    <th>Owner Name</th>
      <th>Destination</th>
      <th>Starting Time</th>
      <th>Arriving Time</th>
      <th>Owner's Passenger Number</th>
      <th>Share or not</th>
      <th>Max Share Number</th>
      <th>Sharer Name</th>
      <th>Sharer's Passenger Number</th>
      <th>Driver Name</th>
      <th>Vehicle Type</th>              
      <th>License Plate Number</th>      
      <th>Maximum Passenger Capacity</th>
  </tr>
  {% for ride in object_list %}
  <tr>
{% if ride.status == 0 %}                                               
    <th>Open</th>                                                       
{% elif ride.status == 1%}                                              
    <th>Confirmed</th>                                                  
{% else %}                                                                  
    <th>Complete</th>                                                   
{% endif %}                                                             
<th><a href="{% url 'ride:driver-complete' ride.id %}">Complete</a></th>
  
      <th>{{ ride.owner.username }}</th>
      <th>{{ ride.des }}</th>
      <th>{{ ride.start_date|date:"F d, Y" }}</th>
      <th>{{ ride.arrive_date|date:"F d, Y" }}</th>
      <th>{{ ride.pas_num }}</th>
      <th>{{ ride.share_valid }}</th>
      <th>{{ ride.share_max_num }}</th>
      <th>{{ ride.share_name }}</th>
      <th>{{ ride.share_number }}</th>
      <th>{{ ride.driver_name }}</th>
      
<th>{{ ride.vehicle_type }}</th>        
<th>{{ ride.license_plate_number }}</th>
<th>{{ ride.max_pas_num }}</th>         

      
    </tr>
  {% endfor %}
</table>
{% endblock content %}

web-app/ride/templates/ride/home.html
{% extends 'ride/base.html' %}

{% block content %}
<h1>Please Choose Your Role:</h1>
<div>
    <button onclick="window.location.href='{% url 'ride:owner-home' %}'">Owner</button> <br><br>
    <button onclick="window.location.href='{% url 'ride:sharer-home' %}'">Sharer</button> <br><br>
    {% if user.profile.isDriver %}
    <button onclick="window.location.href='{% url 'ride:driver-home' %}'">Driver</button> <br><br>
    {% else %}
    <button onclick="window.location.href='{% url 'profile' %}'">Register as a driver</button> <br><br>
    {% endif %}
</div>
{% endblock content %}

web-app/ride/templates/ride/owner.html
{% extends 'ride/base.html' %}

{% block content %}
<h1>Which Action Do You Want?</h1>
<div>
    <button onclick="window.location.href='{% url 'ride:owner-request' %}'">Open a new request</button> <br><br>
    <button onclick="window.location.href='{% url 'ride:owner-view' %}'">View request history</button> <br><br>
</div>
{% endblock content %}

web-app/ride/templates/ride/owner_request.html
{% extends 'ride/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom md-4">Join Today</legend>

                {{ form|crispy }}

            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Submit</button>
            </div>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">
                Already Have An Accound? <a class="ml-2" href="{% url 'login' %}">Sign In</a>
            </small>
        </div>
    </div>
{% endblock content %}

web-app/ride/templates/ride/ride_confirm_delete.html
{% extends 'ride/base.html' %}

{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom md-4">Delete Ride</legend>
                <h2>Are you sure you want to delete the ride?"{{ object.des }}"</h2>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-danger" type="submit" href="{% url 'ride:owner-view'%}">Yes, Delete</button>
                <a class="btn btn-outline-secondary" href="{% url 'ride:owner-view'%}">Cancel</a>
            </div>
        </form>
    </div>
{% endblock content %}

web-app/ride/templates/ride/ride_detail.html
{% extends 'ride/base.html' %}

{% block content %}
    <article class="media content-section">
      <img class="rounded-circle article-img" src="{{ object.owner.profile.image.url }}"    >
      <div class="media-body">
        <div class="article-metadata">
          <a class="mr-2" href="#">{{ object.owner }}</a>
          <small class="text-muted">{{ object.date_started|date:"F d, Y" }}</small>
        </div>
        <h2 class="article-title">{{ object.des }}</h2>
      </div>
    </article>
{% endblock content %}

web-app/ride/templates/ride/ride_form.html
{% extends 'ride/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom md-4">Create/Update Your Ride Request</legend>

                {{ form|crispy }}

            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Submit</button>
            </div>
        </form>
    </div>
{% endblock content %}

web-app/ride/templates/ride/share_form.html
{% extends 'ride/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom md-4">Share Ride Request</legend>

                {{ form|crispy }}

            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit" onclick="window.location.href='{% url 'ride:share-list' %}'">Submit</button>
            </div>
        </form>
    </div>
{% endblock content %}

web-app/ride/templates/ride/share_list.html
{% extends 'ride/base.html' %}
{% block content %}
<table class="table table-striped table-bordered">
  <tr>
    <th>status</th>
    <th>Join</th>  
    <th>owner name</th>
    <th>destination</th>
    <th>leaving time</th>
    <th>arriving time</th>
    <th>passenger number</th>
    <th>share or not</th>
    <th>share max number</th>
    <th>share name</th>
    <th>share number</th>
    <th>driver name</th>
    <th>Vehicle Type</th>              
    <th>License Plate Number</th>      
    <th>Maximum Passenger Capacity</th>

    
  </tr>
  {% for ride in object_list %}
  <tr>
    {% if ride.status == 0 %}                                      
        <th>Open</th>                                              
    {% elif ride.status == 1%}                                     
        <th>Confirmed</th>                                         
    {% else %}                                                     
        <th>Complete</th>                                          
    {% endif %}                                                    
    <th><a href="{% url 'ride:share-join' ride.id %}">Join</a></th>
    
      <th>{{ ride.owner.username }}</th>
      <th>{{ ride.des }}</th>
      <th>{{ ride.start_date|date:"F d, Y" }}</th>
      <th>{{ ride.arrive_date|date:"F d, Y" }}</th>
      <th>{{ ride.pas_num }}</th>
      <th>{{ ride.share_valid }}</th>
      <th>{{ ride.share_max_num }}</th>
      <th>{{ ride.share_name }}</th>
      <th>{{ ride.share_number }}</th>
    <th>{{ ride.driver_name }}</th>
    <th>{{ ride.vehicle_type }}</th>        
    <th>{{ ride.license_plate_number }}</th>
    <th>{{ ride.max_pas_num }}</th>         
    
    </tr>
  {% endfor %}
</table>
{% endblock content %}

web-app/ride/templates/ride/share_update.html
{% extends 'ride/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom md-4">Please update your ride</legend>
                <p>You can only update the passenger number. Because other change other info will make your ride invalid.</p>

                {{ form|crispy }}

            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Submit</button>
            </div>
        </form>
    </div>
{% endblock content %}

web-app/ride/templates/ride/sharer.html
{% extends 'ride/base.html' %}

{% block content %}
<h1>Which Action Do You Want?</h1>
<div>
    <button onclick="window.location.href='{% url 'ride:share-request' %}'">Open a new request</button> <br><br>
    <button onclick="window.location.href='{% url 'ride:share-view' %}'">View request history</button> <br><br>
</div>
{% endblock content %}